name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@main
      env:
        HUGO_EXTENDED: true
        HUGO_VERSION: 0.105.0
        GO_VERSION: 1.19.3
        TARGET_REPO: FICTION-ZJU/FICTION-ZJU.github.io
        TARGET_BRANCH: main
        TOKEN: ${{ secrets.WOWCHEMY_DEPLOY_TOKEN }}
        # CNAME: www.fiction.github.io
